<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke Test" duration-ms="80427" started-at="2017-09-27T13:22:30Z" finished-at="2017-09-27T13:23:51Z">
    <groups>
    </groups>
    <test name="Smoke Testcases" duration-ms="80427" started-at="2017-09-27T13:22:30Z" finished-at="2017-09-27T13:23:51Z">
      <class name="MobileCloudComputing.startappium">
        <test-method status="PASS" signature="appium()[pri:0, instance:MobileCloudComputing.startappium@4439f31e]" name="appium" is-config="true" duration-ms="5" started-at="2017-09-27T13:22:30Z" finished-at="2017-09-27T13:22:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appium -->
        <test-method status="PASS" signature="killappium()[pri:0, instance:MobileCloudComputing.startappium@4439f31e]" name="killappium" is-config="true" duration-ms="0" started-at="2017-09-27T13:23:51Z" finished-at="2017-09-27T13:23:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- killappium -->
      </class> <!-- MobileCloudComputing.startappium -->
      <class name="MobileCloudComputing.AppTest">
        <test-method status="PASS" signature="InstallAPK()[pri:0, instance:MobileCloudComputing.AppTest@5dfcfece]" name="InstallAPK" is-config="true" duration-ms="11961" started-at="2017-09-27T13:22:30Z" finished-at="2017-09-27T13:22:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InstallAPK -->
        <test-method status="FAIL" signature="BarcodeTest()[pri:0, instance:MobileCloudComputing.AppTest@5dfcfece]" name="BarcodeTest" duration-ms="16976" started-at="2017-09-27T13:22:42Z" description="QR Code photo" finished-at="2017-09-27T13:22:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.Exception: Internal Error. Could not load test case.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at org.testng.Assert.fail(Assert.java:94)
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.BarcodeTest(AppTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BarcodeTest -->
        <test-method status="PASS" signature="LandscapeTest()[pri:0, instance:MobileCloudComputing.AppTest@5dfcfece]" name="LandscapeTest" duration-ms="15289" started-at="2017-09-27T13:22:59Z" description="Landscape photo" finished-at="2017-09-27T13:23:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LandscapeTest -->
        <test-method status="FAIL" signature="LargeLandscapeTest()[pri:0, instance:MobileCloudComputing.AppTest@5dfcfece]" name="LargeLandscapeTest" duration-ms="18751" started-at="2017-09-27T13:23:15Z" description="Giant landscape photo. Are you handling well the memory?" finished-at="2017-09-27T13:23:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.Exception: Internal Error. Could not load test case.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at org.testng.Assert.fail(Assert.java:94)
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.LargeLandscapeTest(AppTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LargeLandscapeTest -->
        <test-method status="FAIL" signature="SelfieTest()[pri:0, instance:MobileCloudComputing.AppTest@5dfcfece]" name="SelfieTest" duration-ms="17438" started-at="2017-09-27T13:23:33Z" description="Selfie photo" finished-at="2017-09-27T13:23:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.Exception: Internal Error. Could not load test case.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at org.testng.Assert.fail(Assert.java:94)
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.SelfieTest(AppTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SelfieTest -->
      </class> <!-- MobileCloudComputing.AppTest -->
    </test> <!-- Smoke Testcases -->
  </suite> <!-- Smoke Test -->
</testng-results>
